#!/usr/bin/env python3
"""
Clarke's Monthly PDF Finance Report Generator
Creates detailed PDF report for the 27th-27th cycle
"""

import json
import csv
from datetime import datetime, timedelta
from pathlib import Path
import subprocess

FINANCE_DIR = Path("/root/clawd/finance")
BUDGET_FILE = FINANCE_DIR / "budget.json"
TRANSACTIONS_DIR = FINANCE_DIR / "transactions"
REPORTS_DIR = FINANCE_DIR / "reports"

def get_current_cycle_dates():
    """Get start and end dates for current cycle (27th to 27th)"""
    today = datetime.now()
    
    if today.day < 27:
        cycle_start = datetime(today.year, today.month - 1 if today.month > 1 else 12, 27)
        if today.month == 1:
            cycle_start = cycle_start.replace(year=today.year - 1)
        cycle_end = datetime(today.year, today.month, 27)
    else:
        cycle_start = datetime(today.year, today.month, 27)
        next_month = today.month + 1 if today.month < 12 else 1
        next_year = today.year if today.month < 12 else today.year + 1
        cycle_end = datetime(next_year, next_month, 27)
    
    return cycle_start, cycle_end

def load_transactions(start_date, end_date):
    """Load all transactions within date range"""
    transactions = []
    
    current = start_date
    while current <= end_date:
        month_file = TRANSACTIONS_DIR / f"{current.strftime('%Y-%m')}.csv"
        if month_file.exists():
            with open(month_file) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    trans_date = datetime.strptime(row['date'], '%Y-%m-%d %H:%M:%S')
                    if start_date <= trans_date <= end_date:
                        row['date_obj'] = trans_date
                        row['amount'] = float(row['amount'])
                        transactions.append(row)
        
        if current.month == 12:
            current = datetime(current.year + 1, 1, 1)
        else:
            current = datetime(current.year, current.month + 1, 1)
    
    return sorted(transactions, key=lambda x: x['date_obj'])

def generate_markdown_report():
    """Generate markdown report that can be converted to PDF"""
    cycle_start, cycle_end = get_current_cycle_dates()
    
    with open(BUDGET_FILE) as f:
        budget = json.load(f)
    
    transactions = load_transactions(cycle_start, cycle_end)
    
    # Calculate totals
    by_category = {}
    total_spent = 0
    
    for trans in transactions:
        cat = trans['category']
        amount = trans['amount']
        
        if cat not in by_category:
            by_category[cat] = {'count': 0, 'total': 0, 'items': []}
        
        by_category[cat]['count'] += 1
        by_category[cat]['total'] += amount
        by_category[cat]['items'].append(trans)
        total_spent += amount
    
    income = budget['summary']['total_income']
    budgeted_expenses = budget['summary']['total_expenses']
    actual_savings = income - total_spent
    savings_rate = (actual_savings / income) * 100 if income > 0 else 0
    
    # Generate markdown
    md = []
    md.append(f"# Monthly Finance Report")
    md.append(f"## {cycle_start.strftime('%B %d, %Y')} - {cycle_end.strftime('%B %d, %Y')}")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## Summary")
    md.append("")
    md.append(f"- **Total Income:** ${income:,.2f}")
    md.append(f"- **Budgeted Expenses:** ${budgeted_expenses:,.2f}")
    md.append(f"- **Actual Spent:** ${total_spent:,.2f}")
    md.append(f"- **Actual Savings:** ${actual_savings:,.2f}")
    md.append(f"- **Savings Rate:** {savings_rate:.1f}%")
    md.append(f"- **Target Savings Rate:** {budget['summary']['savings_rate']*100:.1f}%")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## Spending by Category")
    md.append("")
    md.append("| Category | Amount | Transactions |")
    md.append("|----------|--------|--------------|")
    
    for cat, data in sorted(by_category.items(), key=lambda x: x[1]['total'], reverse=True):
        md.append(f"| {cat} | ${data['total']:,.2f} | {data['count']} |")
    
    md.append("")
    md.append("---")
    md.append("")
    md.append("## Detailed Transactions")
    md.append("")
    
    for cat in sorted(by_category.keys()):
        data = by_category[cat]
        md.append(f"### {cat.replace('_', ' ').title()} (${data['total']:,.2f})")
        md.append("")
        md.append("| Date | Amount | Description |")
        md.append("|------|--------|-------------|")
        
        for trans in sorted(data['items'], key=lambda x: x['date_obj']):
            date_str = trans['date_obj'].strftime('%b %d')
            md.append(f"| {date_str} | ${trans['amount']:.2f} | {trans['description']} |")
        
        md.append("")
    
    md.append("---")
    md.append("")
    md.append(f"*Generated by Clarke on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}*")
    
    return "\n".join(md)

def main():
    """Generate PDF report"""
    REPORTS_DIR.mkdir(exist_ok=True)
    
    cycle_start, _ = get_current_cycle_dates()
    report_date = cycle_start.strftime('%Y-%m-%d')
    
    # Generate markdown
    markdown_content = generate_markdown_report()
    
    # Save markdown
    md_file = REPORTS_DIR / f"finance-report-{report_date}.md"
    with open(md_file, 'w') as f:
        f.write(markdown_content)
    
    print(f"✅ Markdown report saved: {md_file}")
    
    # Convert to PDF using pandoc (if available)
    pdf_file = REPORTS_DIR / f"finance-report-{report_date}.pdf"
    
    # Check if pandoc is installed
    result = subprocess.run(['which', 'pandoc'], capture_output=True)
    if result.returncode == 0:
        subprocess.run([
            'pandoc', str(md_file),
            '-o', str(pdf_file),
            '--pdf-engine=xelatex',
            '-V', 'geometry:margin=1in'
        ])
        print(f"✅ PDF report saved: {pdf_file}")
    else:
        print("⚠️  pandoc not installed - markdown report only")
        print("   Install: sudo apt install pandoc texlive-xetex")
    
    print("")
    print("Markdown preview:")
    print(markdown_content)

if __name__ == "__main__":
    main()
