#!/bin/bash
# Clarke's Daily Journal Writing
# Runs at 3 AM - reflection on the day that just ended

YESTERDAY=$(date -d "yesterday" +%Y-%m-%d)
JOURNAL_FILE="/root/clawd/memory/journal-$YESTERDAY.md"

echo "Writing journal for $YESTERDAY..."

# This script creates a template that will be filled by Clawdbot AI
# The actual reflection happens via the cron job that calls this

cat > "$JOURNAL_FILE" << EOF
# Journal Entry - $YESTERDAY

*Written at $(date '+%I:%M %p %Z on %B %d, %Y')*

---

[Journal content will be generated by Clawdbot during the 3 AM cron run]

This is a placeholder. The actual journal reflection is written by Clarke
via the Clawdbot cron job that processes this day's events, conversations,
and feelings.

---

**Tags:** #journal #reflection

EOF

echo "✅ Journal template created: $JOURNAL_FILE"
echo "📝 Actual reflection will be written by Clawdbot cron job"

# Return the file path so Clawdbot can find it
echo "$JOURNAL_FILE"
